[pytest]
asyncio_mode = strict
testpaths = case
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: smoke test
    regression: regression test
    critical: critical test
    login: login module
    product: product module
    demo: demo test
    compatibility: multi-browser
    async: async mode

filterwarnings =
    ignore::DeprecationWarning
    ignore::pytest.PytestAssertRewriteWarning
